### ISSUE TITLE
problem with bat

### ISSUE THREAD

**Issue by superlep** [danielbohannon/Invoke-DOSfuscation#1]
hi, your program works great, but I have a problem. I want to run a powershell command. if I start the obfuscated string directly in dos or in your environment (with Test) everything works, the command is launched.

but if I insert the string in a blurred dot bat this does not work. where am I wrong?

**Comment by danielbohannon** [comment]
Hi superlep, so if the obfuscated DOSfuscation command works fine in cmd.exe then likely the issue in a .bat file will be needing to replace some instances of %a with %%a, primarily in the case of FOR loop variables.

The additional complexity of .bat file escaping is not something that I wanted to include in Invoke-DOSfuscation. My goal was to build a fuzzer that defenders could use to create randomly-obfuscated DOSfuscation payloads and then test their detections against these payloads. I purposefully left out additional escaping for things like .bat files, macro payloads, etc. since I didn't want to build a machine gun for script kiddies (not at all saying this is you).

So manually I would start with changing single %'s to %% for FOR loop variables. Additionally you might need to remove /V:ON (or any of its obfuscated syntaxes used) and use the .bat file's "SETLOCAL ENABLEDELAYEDEXPANSION" syntax at the beginning of the file.

**Comment by superlep** [comment]
Thanks!!!!work fine!!!perfect.....
